/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StaffSaleController;
import model.DrinkStore;

/**
 *
 * @author ACER
 */
public class StaffDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StaffDashboard.class.getName());

    private StaffSaleController staffSale; 
    private DrinkStore drinkStore;
    public StaffDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        drinkStore = new DrinkStore();
        staffSale = new StaffSaleController(drinkStore,this);
    }
    
    //getter for textfield
    public String getID()
    {
        return txtID.getText();
    }
    public String getQuantity()
    {
        return txtQuantity.getText();
    }
   
    public javax.swing.JTable getTable()
    {
        return jTableAvailableDrinks;
    }
    
    public void clearForm()
    {
        txtID.setText("");
        txtQuantity.setText("");
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanelStaffDashBoard = new javax.swing.JPanel();
        JLabel_Welcome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        proceesSalePanel = new javax.swing.JPanel();
        jLabel_ProcessSale = new javax.swing.JLabel();
        jLabel_ID = new javax.swing.JLabel();
        jLabel_quantity = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jButton_ProcessSale = new javax.swing.JButton();
        jButton_Logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAvailableDrinks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabel_Welcome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JLabel_Welcome.setText("WELCOME");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        proceesSalePanel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel_ProcessSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ProcessSale.setText("Start Your Sales Journey....");

        jLabel_ID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ID.setText("Enter ID :");

        jLabel_quantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_quantity.setText("Enter Quantity :");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jButton_ProcessSale.setBackground(new java.awt.Color(255, 204, 204));
        jButton_ProcessSale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ProcessSale.setText("Process Sale");
        jButton_ProcessSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProcessSaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout proceesSalePanelLayout = new javax.swing.GroupLayout(proceesSalePanel);
        proceesSalePanel.setLayout(proceesSalePanelLayout);
        proceesSalePanelLayout.setHorizontalGroup(
            proceesSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceesSalePanelLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel_ProcessSale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proceesSalePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proceesSalePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_ProcessSale, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        proceesSalePanelLayout.setVerticalGroup(
            proceesSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceesSalePanelLayout.createSequentialGroup()
                .addComponent(jLabel_ProcessSale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(proceesSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton_ProcessSale, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jButton_Logout.setBackground(new java.awt.Color(255, 102, 153));
        jButton_Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Logout.setText("LOGOUT");
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });

        jTableAvailableDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "    ID", "   Product Name", "    Price", "   Quantity"
            }
        ));
        jScrollPane1.setViewportView(jTableAvailableDrinks);

        javax.swing.GroupLayout mainPanelStaffDashBoardLayout = new javax.swing.GroupLayout(mainPanelStaffDashBoard);
        mainPanelStaffDashBoard.setLayout(mainPanelStaffDashBoardLayout);
        mainPanelStaffDashBoardLayout.setHorizontalGroup(
            mainPanelStaffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelStaffDashBoardLayout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(JLabel_Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(mainPanelStaffDashBoardLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(mainPanelStaffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(proceesSalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelStaffDashBoardLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelStaffDashBoardLayout.setVerticalGroup(
            mainPanelStaffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelStaffDashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelStaffDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabel_Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proceesSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelStaffDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanelStaffDashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        // TODO add your handling code here:
        HomeScreen home = new HomeScreen();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton_ProcessSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProcessSaleActionPerformed
        // TODO add your handling code here:
        staffSale.proceedSaleMethod();
    }//GEN-LAST:event_jButton_ProcessSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StaffDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_Welcome;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JButton jButton_ProcessSale;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_ProcessSale;
    private javax.swing.JLabel jLabel_quantity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAvailableDrinks;
    private javax.swing.JPanel mainPanelStaffDashBoard;
    private javax.swing.JPanel proceesSalePanel;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
